import {
  AudioWaveform,
  BookOpen,
  GalleryVerticalEnd,
  Users,
  Building2,
  Activity,
  Settings,
  FileText,
  Video,
  Newspaper,
  MessageSquare,
  HelpCircle,
  Library,
  Search,
  TrendingUp,
  Wallet,
  Star,
  ClipboardList,
  Shield,
  AlertCircle,
  ThumbsUp,
  Award,
  CreditCard,
  DollarSign,
  PieChart,
  FileBarChart,
  Handshake,
  MapPin,
  Bug,
} from "lucide-react";

export const SidebarData = {
  user: {
    name: "Karn",
    email: "Karan@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  teams: [
    {
      name: "Admin Desk",
      logo: GalleryVerticalEnd,
      plan: "Administration",
      navMain: [
        {
          title: "Explorers",
          url: "explorers",
          icon: Users,
          isActive: true,
        },
        {
          title: "Coaches",
          url: "coaches",
          icon: Users,
          isActive: true,
        },
        {
          title: "Organisations",
          url: "organisations",
          icon: Building2,
          isActive: true,
        },
        {
          title: "Recent Activities",
          url: "activities",
          icon: Activity,
          isActive: true,
        },
        {
          title: "Manage",
          url: "#",
          icon: Settings,
          isActive: true,
          items: [
            { title: "Assessments", url: "assessments", icon: FileText },
            { title: "Sessions", url: "sessions", icon: Video },
            { title: "Session Pool", url: "session-pool", icon: Library },
            {
              title: "Consultant Premium",
              url: "consultant-premium",
              icon: Award,
            },
            {
              title: "Masterclasses",
              url: "masterclasses",
              icon: ClipboardList,
            },
            { title: "Courses", url: "courses", icon: BookOpen },
            { title: "Access Codes", url: "access-codes", icon: Shield },
            { title: "Desk Users", url: "users", icon: Users },
          ],
        },
      ],
    },
    {
      name: "Approval Desk.",
      logo: AudioWaveform,
      plan: "Approvals",
      navMain: [
        {
          title: "Approval Desk",
          url: "approval",
          icon: ThumbsUp,
        },
        {
          title: "Coaches Profiles",
          url: "payments",
          icon: Users,
        },
        {
          title: "Organisations Profiles",
          url: "payout",
          icon: Building2,
        },
        {
          title: "Google Map Listing",
          url: "google-map",
          icon: MapPin,
        },
        {
          title: "Forms",
          url: "forms",
          icon: FileText,
        },
      ],
    },
    {
      name: "Digital Desk.",
      logo: AudioWaveform,
      plan: "Digital Content",
      navMain: [
        // {
        //   title: "Digital Desk",
        //   url: "#",
        //   icon: Monitor,
        // },
        {
          title: "Contents",
          url: "#",
          icon: FileText,
          items: [
            { title: "Insights", url: "insights", icon: TrendingUp },
            { title: "Video library", url: "video-library", icon: Video },
            { title: "In the news", url: "in-news", icon: Newspaper },
            { title: "Testimonials", url: "testimonials", icon: MessageSquare },
            { title: "Libraries", url: "library", icon: Library },
            { title: "Help Articles", url: "help-articles", icon: HelpCircle },
            { title: "FAQs", url: "faqs", icon: HelpCircle },
            { title: "Team Profiles", url: "teams", icon: Users },
          ],
        },
      ],
    },
    {
      name: "Relations Desk.",
      logo: AudioWaveform,
      plan: "Relations",
      navMain: [
        {
          title: "Relation Desk",
          url: "relation",
          icon: Handshake,
        },
        {
          title: "User/Org Search",
          url: "user-org-search",
          icon: Search,
        },
        {
          title: "Leads",
          url: "#",
          icon: TrendingUp,
          items: [
            { title: "Active Users", url: "active-users", icon: Users },
            { title: "Explorers", url: "explorers", icon: Users },
            { title: "Coaches", url: "coaches", icon: Users },
            { title: "Partners", url: "partners", icon: Handshake },
          ],
        },
        {
          title: "Supports",
          url: "#",
          icon: AlertCircle,
          items: [
            { title: "Problems", url: "problems", icon: AlertCircle },
            { title: "Bugs", url: "bugs", icon: Bug },
            { title: "Abuses", url: "abuses", icon: Shield },
          ],
        },
        {
          title: "Feedback",
          url: "feedback",
          icon: MessageSquare,
        },
        {
          title: "Review",
          url: "review",
          icon: Star,
        },
      ],
    },
    {
      name: "Finance Desk.",
      logo: AudioWaveform,
      plan: "Finance",
      navMain: [
        {
          title: "Finance Desk",
          url: "finance",
          icon: Wallet,
        },
        {
          title: "Payments",
          url: "payments",
          icon: CreditCard,
        },
        {
          title: "Payouts",
          url: "payout",
          icon: DollarSign,
        },
        {
          title: "P&L",
          url: "pl",
          icon: PieChart,
        },
        {
          title: "Reports",
          url: "reports",
          icon: FileBarChart,
        },
      ],
    },
  ],
};
